### ISSUE TITLE
Support boolean types

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#107]
part of #17

see https://www.postgresql.org/docs/12/datatype-boolean.html

**Comment by lpiepiora** [comment]
Hi @alex-dukhno I'd like to try to take on this one.

**Comment by lpiepiora** [comment]
@alex-dukhno quick question, do we want to support here also casting of string types, like described here (and if so should the parser know the datatype without explicit casting?):

> The datatype input function for type boolean accepts these string representations for the “true” state:
> true
> yes
> on
> 1
>
> and these representations for the “false” state:
>
> false
> no
> off
> 0
> 
> Unique prefixes of these strings are also accepted, for example t or n. Leading or trailing whitespace is ignored, and case does not matter.

**Comment by alex-dukhno** [comment]
Good question! About which I haven't thought 😄 
We can start with `true` and `false`, but yeah it would be good to have all other variants.
I actually started to play with it. All of the following queries are valid:
```sql
insert into booleans values ('y');
insert into booleans values ('yes');
insert into booleans values ('t');
```

I think for `true` and `false` we have to use `Boolean(bool)` value https://github.com/ballista-compute/sqlparser-rs/blob/main/src/ast/value.rs#L35 and for string casting we could try to use `TypedString { data_type: DataType, value: String }` https://github.com/ballista-compute/sqlparser-rs/blob/main/src/ast/mod.rs#L216

**Comment by lpiepiora** [comment]
Yes, I have implemented it for `TRUE` and `FALSE`. It's fairly simple I believe to implement it with the explicit casting, like so `'y'::boolean` or `'yes'::boolean` (given the Enum value you've provided, because then you get a Typed String back). 

I'm not sure though how to do it without explicit casting - I will have to look closer in the code. Also the spec says it can be `NULL`, but I guess this is not really for the Boolean type, as `NULL` seems to be a bit more generic, right?

**Comment by alex-dukhno** [comment]
I think you can do that with `BooleanTypeConstraint`, `Constraint::validate` accepts `&str` so you can return `true` when user provide one of `'y', 'yes', 'n', 'no'` and so forth and `Serializer::ser` can parse that into `rust` `bool` type and then serialize into `Vec<u8>`
