### ISSUE TITLE
Unify insert and update constraint checks

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#142]
`FrontendStorage::insert_into` and `FrontendStorage::update_all` have identical logic of handling type constraint violations. It could be refactored into separate function inside `impl FrontendStorage` block

**Comment by vkulichenko** [comment]
Hi Alex! I would like to participate in the project, and this issue looks like a good start. Could you assign it to me? Thanks!

**Comment by vkulichenko** [comment]
@alex-dukhno Alex, I've reviewed the logic in question. One thing I've noticed is that error vectors are added only for the rows that have at least one error. Therefore, if you insert 100 rows, where just one contains an error, the resulting `errors` map will contain only one vector. As far as I can tell, there is no way to trace this vector back to the failed row. I'm not sure if that's an issue, but it looks a bit suspicious to me. Is this design intentional?

**Comment by alex-dukhno** [comment]
If I understand you correctly then your concern about tracing row with error should be fixed by https://github.com/alex-dukhno/database/issues/153

**Comment by vkulichenko** [comment]
Yes, that's exactly what I mean. It looks like #153 already has a PR. It modifies the same piece of code, so I think it makes sense for me to wait for it to be merged to avoid conflicts. Let me know if you think otherwise.

**Comment by alex-dukhno** [comment]
#153 is closed so I think you are unblocked

**Comment by vkulichenko** [comment]
@alex-dukhno Pull request is created. After changes in #153, code duplication was already minimal, so my refactoring is rather minor. I've tried to make the code a little cleaner though.

Let me know if there is anything else you would like to improve here.
