### ISSUE TITLE
Insertion should be aborted after first row with constraint violations

### ISSUE THREAD

**Issue by alex-dukhno** [alex-dukhno/database#153]
If user inserts multiple records within single insert like:
```sql
insert into table values (1, 2, 3), (<smallint::max>, <smallint::max>, 0), (<smallint::max>, 0, 0);
```
An insert should be aborted after `(<smallint::max>, <smallint::max>, 0)` record. However, error still should report two constraint violations for the first and the second columns

Nice to have record index in the error message 

Good entry point is to examine the following test https://github.com/alex-dukhno/database/pull/152/files#diff-ae39057dfc859e4b9cf67396d323baeeR449

**Comment by alex-dukhno** [comment]
Interesting question is how to report errors when user updates record with `SET col1 = <max_value> + 1`.

**Comment by AndrewBregger** [comment]
@alex-dukhno could you assign this to me? Thanks.

**Comment by alex-dukhno** [comment]
@AndrewBregger are you going to work on both issues? If so please create separate PRs for each, I don't want that one blocks the other.

Thanks

**Comment by AndrewBregger** [comment]
> Interesting question is how to report errors when user updates record with SET col1 = <max_value> + 1.
To answer what I think about this question. I think updates should follow the same rules for this as insert does. When an error occurs during an update the entire operation should be aborted and any operations completed operations should be undone.

In the situation you give, the first row would generate an error; therefore, the rest of the rows would not be processed due to the error.

Let's say an error occurs on a column where we are performing `set col1 = col1 + 1` and col1 already is `max_value>` and this column is in the middle of the table. The operations that have already been performed should be discarded, the rest of the rows should be ignored, and an error generated.

What do you think?

**Comment by alex-dukhno** [comment]
Seems like I have very unordered ideas ... https://github.com/alex-dukhno/database/issues/153#issuecomment-655419623 is more relevant to an idea in #154
